// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgiLbkyBa970nch79yAjmiZEpahxaNQZo',
    appId: '1:199203356591:web:ca9d1b4c989e4d4c58795a',
    messagingSenderId: '199203356591',
    projectId: 'sprintjournal-70308',
    authDomain: 'sprintjournal-70308.firebaseapp.com',
    storageBucket: 'sprintjournal-70308.firebasestorage.app',
    measurementId: 'G-YQB316W9ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH-QhT4GjIHctzVMdHH9S1ZDa8dni6NWA',
    appId: '1:199203356591:android:7163d8d72b32cd2058795a',
    messagingSenderId: '199203356591',
    projectId: 'sprintjournal-70308',
    storageBucket: 'sprintjournal-70308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg7RLbYIA7FP_1mDX3lLYllAwqaJh0cig',
    appId: '1:199203356591:ios:c8d621733b609c6458795a',
    messagingSenderId: '199203356591',
    projectId: 'sprintjournal-70308',
    storageBucket: 'sprintjournal-70308.firebasestorage.app',
    iosBundleId: 'com.example.sprintJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg7RLbYIA7FP_1mDX3lLYllAwqaJh0cig',
    appId: '1:199203356591:ios:c8d621733b609c6458795a',
    messagingSenderId: '199203356591',
    projectId: 'sprintjournal-70308',
    storageBucket: 'sprintjournal-70308.firebasestorage.app',
    iosBundleId: 'com.example.sprintJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgiLbkyBa970nch79yAjmiZEpahxaNQZo',
    appId: '1:199203356591:web:85bf4cb118cc10fd58795a',
    messagingSenderId: '199203356591',
    projectId: 'sprintjournal-70308',
    authDomain: 'sprintjournal-70308.firebaseapp.com',
    storageBucket: 'sprintjournal-70308.firebasestorage.app',
    measurementId: 'G-JLS4WZSDY7',
  );
}
